### ISSUE TITLE
请问一下安装后如何使用组件

### ISSUE THREAD

**Issue by AnhTom2000** [HenrryShaw/vue-calendar#1]

**Comment by HenrryShaw** [comment]
在项目的demo文件夹下有具体的例子


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Weleness"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月12日(星期天) 晚上9:42
收件人:&nbsp;"HenrryShaw/vue-calendar"<vue-calendar@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[HenrryShaw/vue-calendar] 请问一下安装后如何使用组件 (#1)

**Comment by AnhTom2000** [comment]
好的,谢谢!
